-- MySQL Workbench Synchronization
-- Generated: 2019-02-21 22:07
-- Model: New Model
-- Version: 1.0
-- Project: NetworkingWebsite
-- Author: Almicke Navarro

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`USERS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(45) NULL DEFAULT NULL,
  `LASTNAME` VARCHAR(45) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `USERNAME` VARCHAR(45) NULL DEFAULT NULL,
  `PASSWORD` VARCHAR(45) NULL DEFAULT NULL,
  `ROLE` INT(11) NULL DEFAULT NULL,
  `SUSPEND` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`EDUCATION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SCHOOL` VARCHAR(45) NULL DEFAULT NULL,
  `DEGREE` VARCHAR(45) NULL DEFAULT NULL,
  `START_YEAR` VARCHAR(45) NULL DEFAULT NULL,
  `END_YEAR` VARCHAR(45) NULL DEFAULT NULL,
  `ADDITIONAL_INFORMATION` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_EDUCATION_USERS_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_EDUCATION_USERS`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`WORK_EXPERIENCE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `POSITION` VARCHAR(45) NULL DEFAULT NULL,
  `COMPANY` VARCHAR(45) NULL DEFAULT NULL,
  `START_YEAR` VARCHAR(45) NULL DEFAULT NULL,
  `END_YEAR` VARCHAR(45) NULL DEFAULT NULL,
  `ADDITIONAL_INFORMATION` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_WORK_EXPERIENCE_USERS1_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_WORK_EXPERIENCE_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`PERSONAL_INFORMATION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BIOGRAPHY` VARCHAR(45) NULL DEFAULT NULL,
  `CURRENT_POSITION` VARCHAR(45) NULL DEFAULT NULL,
  `CONTACT_EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(45) NULL DEFAULT NULL,
  `PHOTO` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_PERSONAL_INFORMATION_USERS1_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_PERSONAL_INFORMATION_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`SKILLS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `SKILLS_NAME` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_SKILLS_USERS1_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_SKILLS_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`ADDRESSES` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STREET_ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  `CITY` VARCHAR(45) NULL DEFAULT NULL,
  `STATE` VARCHAR(45) NULL DEFAULT NULL,
  `ZIP_CODE` INT(11) NULL DEFAULT NULL,
  `USERS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_ADDRESSES_USERS1_idx` (`USERS_ID` ASC),
  CONSTRAINT `fk_ADDRESSES_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`GROUPS` (
  `ID` INT(11) NOT NULL,
  `GROUP_NAME` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `NetworkingWebsite`.`USER_GROUPS` (
  `ID` INT(11) NOT NULL,
  `USERS_ID` INT(11) NOT NULL,
  `GROUPS_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `USERS_ID`),
  INDEX `fk_USER_GROUPS_USERS1_idx` (`USERS_ID` ASC, `GROUPS_ID` ASC),
  INDEX `fk_USER_GROUPS_GROUPS1_idx` (`GROUPS_ID` ASC),
  CONSTRAINT `fk_USER_GROUPS_USERS1`
    FOREIGN KEY (`USERS_ID` , `GROUPS_ID`)
    REFERENCES `NetworkingWebsite`.`USERS` (`ID` , `ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER_GROUPS_GROUPS1`
    FOREIGN KEY (`GROUPS_ID`)
    REFERENCES `NetworkingWebsite`.`GROUPS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
